/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

// eslint-disable-next-line no-unused-vars
import React, { Component } from 'react';
import 'react-native-gesture-handler';
import { createAppContainer } from 'react-navigation';
import { createStackNavigator } from 'react-navigation-stack';
import RangingBeacons from './src/ranging'

const AppNavigator = createStackNavigator({
  Home: {
    screen: RangingBeacons,
  },
});

// eslint-disable-next-line no-unused-vars
const AppContainer = createAppContainer(AppNavigator);

export default class App extends React.Component {
  render() {
    return <AppContainer />;
  }
}